### ISSUE TITLE
[Bug / FE] Header 터치 스크롤 이벤트시 이벤트 전파 문제

### ISSUE THREAD

**Issue by seoko97** [woowa-techcamp-2022/web-kiosk-seokho#8]
# 문제

터치 스크롤 이벤트 구현중 NavItem을 foucs하고 이벤트를 실행하면 NavItem이 click되어 버그가 발생합니다.

초기 생각한 로직은
1. mousedown시 가로 스크롤 시작
2. mousemove시 스크롤
3. mouseup시 스크롤 종료

https://user-images.githubusercontent.com/60173534/183297798-1c8f00cb-dda3-4002-9b1d-2f560bd1f22a.mov

영상과 같이 이벤트가 중복적으로 실행됩니다.

**Comment by seoko97** [comment]
```ts
  const [dragStart] = useScrollXTouchSlide(ref);

  const onClickNavItem: MouseEventHandler<HTMLDivElement> = useCallback(
    (e) => {
      const dragEnd = new Date().getTime();

      if (dragEnd - dragStart >= 150) return;
      ...
      }
```

다음과 같이 drag 시작 시점을 저장하여 저장된 시간과 현재 시간을 검사하는 로직을 생성했습니다.

**Comment by Hyeondoonge** [comment]
isDrag를 드래그 중인지 확인하는 상태로서 사용해서
mousedown되면 이 값을 true로 바꾸고
isDrag상태가 true이면 onClick 이벤트 처리를 막도록하면 안되려나요...!

**Comment by seoko97** [comment]
해당 로직으로 click시 이미 isDrag가 false라 이벤트가 계속 실행됐습니다ㅠㅠ 
그래서 drag 시점을 저장해 걸린 시간을 계산하는 로직으로 변경했습니다!
